config/routes.rb
Rails.application.routes.draw do
  resources :homes do
        member do
          # get :get_file_delivery
        end
        collection do
          get :thermal
          
        end
      end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def thermal
   render :layout => "print" 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:name, :age, :gender)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_for(home) do |f| %>
  <% if home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.text_area :age %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.text_area :gender %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/_template_thermal_responsive.html.erb
<%= stylesheet_link_tag("homes/_template_thermal_responsive") %>
<!-- Template for  template thermal responsive -->
<div class="receipt-container">
  <div id="receipt">
    <div class="receipt-header">
      <div class="institution_logo">
      </div>
      <div class="institution_header">
        <p class="institution_name">fjkdsbfjk</p>
        <p class="institution_address">sdklnfkl</p>
      </div>
    </div>
    <div class="receipt_title">
     fdfd
    </div>
    <div class="receipt-content">
      <table class="receipt-details">
        <tr class="">
          <td class="left-label">
            fdfd
          </td>
          <td class="bold">
            fdfd
          </td>
        </tr>
        <tr class="">
          <td class="left-label">
           fgfgfd
          </td>
          <td class="">
            gfgfd
          </td>
        </tr>
      </table>
      <hr>
      <table class="student-details">
        <% if 'Student' =='Student' %>
          <tr>
            <td class="left-label">
             dsd
            </td>
            <td class="bold rtl_bracket_fix">
             fdfd
            </tr>
          </td>
          <tr>
            <td class="left-label">
             fdfsd
            </td>
            <td >
              dsfsdf
            </td>
          </tr>
          <tr>
            <td class="left-label">
              dffsdf
            </td>
            <td>
              fdsfsf
            </td>
          </tr>
          <% if true %>
            <tr>
              <td class="left-label">
                fdfdf
              </td>
              <td>
                dfdf
              </td>
            </tr>
          <%end %>
        <% elsif v['payee']['type'] =='Employee' %>
          <tr>
            <td class="left-label">
              sdffdsf
            </td>
            <td class="bold">
              dsfsdfd>
            </td>
          </tr>
          <tr>
            <td class="left-label">
              sdfsdf>:
            </td>
            <td>
              sdfsdf
            </td>
          </tr>
          <tr>
            <td class="left-label">
              sdfsdf
            </td>
            <td>
              sdffdsf
            </td>
          </tr>
        <% end %>
        <tr>
          <td class="left-label">
            sdfsdfsdf
          </td>
          <td>
            sdfsdsdf
          </td>
        </tr>
        <tr>
          <% if "stu" == "stu"%>
            <td class="left-label">
              sdfsdfsd
            </td>
            <td>
              asdsads
            </td>
          <% end %>
        </tr>
      </table>
      <section class="particulars-header">
        <div class="particulars-header-left">asdsads</div>
        <div class="particulars-header-right">asdasd</div>
      </section>
      <% if true == true%>
        <%i=0%>
        <section class="particulars">
          <%[1,2,3,4].each do |particular_type|%>
            <%[6,4,7,8].each do |fp|%>
              <div class="receipt-details_item">
                <div class="left"><%=i+=1%>. <%=fp%></div>
                <div class="right"><%=  fp %></div>
              </div>
            <%end%>
          <%end%>
        </section>
      <% else %>
        <div class="particulars">
          <% [9,9,9,9].each_with_index do |particular,index| %>
            <section class="particular_wise_item">
              <div class="particular_name">
                <%= "#{index+1}. #{particular}" %>
              </div>
              <div class="particular_wise_item_details">
                <div class="left">
                  <%=  t('amount') %>
                </div>
                <div class="right">
                  <%= precision_label(particular) %>
                </div>
              </div>
              <% if particular_has_previous_payments(particular) %>
                <div class="particular_wise_item_details">
                  <div class="left">
                    <%= t('remaining_balance') %>
                  </div>
                  <div class="right">
                    <%= precision_label(particular) %>
                  </div>
                </div>
              <% end %>
              <% if particular_has_discount(particular) %>
                <div class="particular_wise_item_details">
                  <div class="left">
                    <%= t('discount') %>
                   </div>
                  <div class="right">
                    - <%= precision_label(particular.discount) %>
                  </div>
                </div>
              <% end %>
              <div class="particular_wise_item_details">
                <div class="left">
                  <%= t('amount_paid') %>
                </div>
                <div class="right">
                  <%= precision_label(particular.amount_paid) %>
                </div>
              </div>
              <div class="particular_wise_item_details">
                <div class="left">
                  <%= t('balance') %>
                </div>
                <div class="right">
                  <%= precision_label(particular.balance) %>
                </div>
              </div>
            </section>
          <% end %>
        </div>
      <% end %>
      <section class="discount">
        <% if true%>
          <p class="subtitle">
            discount
          </p>
        <% end %>
        <%[1,5,5,5].each_with_index do |d,i|%>
          <div class="receipt-details_item">
              <div class="left"><%=i+=1%>.<%= d%></div>
              <div class="right">- <%= d %></div>
          </div>
        <%end%>
      </section>
      <section class="fine">
        <% if true %>
          <p class="subtitle">
            fine
          </p>
        <% end %>
        <%[9,9,9,9].each_with_index do |fine,i|%>
          <div class="receipt-details_item">
              <div class="left "><%=i+=1%>.<%= fine %></div>
              <div class="right"><%= fine %></div>
          </div>
        <%end%>
      </section>
      <section class="summary">
        <p class="subtitle">
          <%= t('summary') %>
        </p>
        <div class="receipt-details_item">
          <div class="left">
            <%= t('total_fees') %>
          </div>
          <div class="right">
            <%= "dsdas" %>
          </div>
        </div>
        <% if true %>
          <div class="receipt-details_item">
            <div class="left">
              <%= t('discount') %>
            </div>
            <div class="right">
              - <%= "dfdsf" %>
            </div>
          </div>
        <% end %>
        <% if true%>
          <div class="receipt-details_item">
            <div class="left">
              <%= t('fine') %>
            </div>
            <div class="right">
              <%= "sdds" %>
            </div>
          </div>
        <% end %>
      </section>
      <section class="payment_status">
        <table class="payment_status-details">
          <tr class="">
            <td class="right-label">
              <%= "dfdfdf" %>:
            </td>
            <td class="bold">
              <%= "dfdfds" %>
            </td>
          </tr>
          <% if true %>
            <tr class="">
              <td class="right-label">
                <%= t('previous_payments') %>:
              </td>
              <td class="bold">
                <%= "fdsdf" %>
              </td>
            </tr>
          <% end %>
          <tr class="">
            <td class="right-label">
              <%= t('amount_paid') %>:
            </td>
            <td class="bold">
              <%= "dsfdsf" %>
            </td>
          </tr>
          <% if true %>
            <tr class="">
              <td class="right-label">
                <%= t('total_amount_paid') %>:
              </td>
              <td class="bold">
                <%= "dfsdf" %>
              </td>
            </tr>
          <% end %>
          <tr class="">
            <td class="right-label">
              <%= t('total_due_amount') %>:
            </td>
            <td class="bold">
              <%= "dsds"%>
            </td>
          </tr>
        </table>
      </section>
      <section class="bottom_fields">
        <table>
          <tr class="receipt-details_item">
            <td class="left">
              <%= t('payment_mode') %>:
            </td>
            <td class="">
              <%= "sdfdsf"%>
            </td>
          </tr>
          <%if true%>
            <tr class="receipt-details_item">
              <td class="left"><%= "sdgfd" %>:</td>
              <td class=""><%= "sdfsd" %></td>
            </div>
          <% end %>
          <%if true%>
            <tr class="receipt-details_item">
              <td class="left">
                <%= t('notes') %>:
              </td>
              <td class="">
                <%= "dffsd" %>
              </td>
            </tr>
          <% end %>
        </table>
      </section>
    </div>
    <div class="receipt-footer">
      <%#= v["payment_note"] %>
    </div>
  </div>
</div>
<%#= debug v %>
<style type="text/css">

/*@media print {*/
  @page {
      margin: 0 10px;
      /*margin-left: 7mm;
      margin-right: 5mm;
      margin-top: 0mm;*/

  }
  body {
    font-size: 9px;
    max-width: 400px;
    min-width: 200px;
    /*font-family: arial;*/
    /*font-family: Lucida Console,Lucida Sans Typewriter,monaco,Bitstream Vera Sans Mono,monospace; */
    font-family: Verdana,Tahoma, Segoe, sans-serif;
    /*max-width: 200px;*/
  }
  .receipt-container {
    margin-bottom: 30px;
    /*width: 300px;*/
    /*border-width: 1px;
    border-style: solid;*/
  }
  .institution_header{
    width: 100%;
    float: left;
    margin-left: 5px;
  }
  .institution_name{
    font-size: 11px;
    /*text-align: center;*/
    font-weight: bold;
    margin-bottom: 5px;
    margin-top: 5px;
  }
  .institution_address {
    font-size: 11px;
  }
  .receipt_title {
    border-top:1px solid black;
    border-bottom:1px solid black;
    text-align: center;
    font-weight: bold;
    font-size: 12px;
    clear: both;
    padding-top: 3px;
    padding-bottom: 3px;
  }
  .institution_logo {
    float: left;
    width: 15%;
    height: 50px;
    border-width: 1px;
    border-color: black;
    border-style: dotted;
    margin-right: 5px;
    display: none;
  }

  .receipt-details {
    /*width: 100%;*/
    margin: 5px;
  }
  .student-details {
    margin: 5px;
  }
  td.left-label {
    padding-right: 10px;
  }
  .left{
    float: left;
    width: 60%;
  }
  .right {
    float: right;
    text-align: right;
    width: 40%;
    word-wrap: break-word;
  }
  .receipt-details_item {
    /*margin-top: 5px;*/
    clear: both;
    line-height: 15px;
    margin-left: 5px;
    margin-right: 5px;
  }
  .receipt-footer{
    color: gray;
    margin: 5px;
  }
  section{
    /*border-bottom:2px solid #333;*/
    border-top:1px solid black;
    /*border-bottom:1px solid black;*/
    border-collapse: collapse;
    clear: both;
    padding-top: 5px;
    padding-bottom: 5px;
    overflow: auto;
    margin-top: -1px; /* workaround for border collapse*/
    margin-bottom: -1px; /* workaround for border collapse*/
  }
  .student-details {

  }
  section.particulars-header {
    border-bottom-width: 0px;
      /*margin-left: 10px;
      margin-right: 10px;*/
  }
  .particulars-header-left {
      float: left;
  }
  .particulars-header-right {
      float: right;
  }
  .payment_status{
    /*font-weight: bold;*/
  }
  .payment_status .left {
    text-align: right;
    width: 70%;
  }
  .payment_status .right {
    /*text-align: right;*/
    width: 30%;
    float: right;
  }
  .bottom_fields{
    clear: both;
  }
  .subtitle {
    /*font-weight: bold;*/
  }
  .particulars-header {
    padding-left: 5px;
    padding-right: 5px;
  }
  .summary p {
    margin-top: 0px;
    margin-left: 5px;
  }
  .discount p {
    margin-top: 0px;
    margin-left: 5px;
  }
  .subtitle {
    margin-top: 0px;
    margin-left: 5px;
  }

  /*Particular wise*/
  .particular_wise_item {

  }
  .particular_wise_item .particular_name{
    font-weight: bold;
    float: left;
    margin-left: 5px;
    margin-right: 5px;
  }
  .particular_wise_item .particular_wise_item_details{
    font-weight: normal;
    float: right;
    width: 100%;
    margin-left: 5px;
    margin-right: 5px;
  }
  .particular_wise_item_details .left {
    width: 70%;
    text-align: right;

  }
  .particular_wise_item_details .right {
    width: 30%;
  }
  .table {
    display: table;
  }
  .table-row {
    display: table-row;
  }
  .table-cell {
    display: table
  }
/*}*/
/* style defaults*/
tr {
  height: 15px;
}
p {
  margin: 1em 0 1em 0;
}
body {
  margin: 1px;
  /*padding: 1em;*/
}

.payment_status-details {
    width: 100%;
}
.payment_status-details tr {

}
.payment_status-details td {

}
.payment_status-details .right-label {
  text-align: right;

}
.payment_status-details .bold {
  float: right;
}
hr {
  background-color: black;
  height: 1px;
  border: 0 none;
  color: black;
}
td.left {
    float: inherit;
    width: inherit;
    padding-right: 5px;
    padding-left: 5px;
    width: 40%;
}


</style>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>
<%= render 'form', home: @home %>
<button type="button" name="button" onclick="print_preview()" class="submit-button"><%= 'Print Sample Receipt' %></button>
<div class="preview_container">
 <iframe src="http://<%=request.host%>:<%=request.port%>/homes/thermal" id="preview_frame" frameborder="0" scrolling="no" onload='javascript:initilize_iframe(this);'></iframe>
</div>
<style type="text/css">
.preview_container {
    float: left;
    clear: both;
    width: 100%;
}

#preview_frame {
  width: 100%;
   margin-left: 202px;
  border-width: 1px;
  border-color: black;
  border-style: solid;
  width: 50%;
  /*margin: 0 auto;*/
  margin-top: 30px;
  margin-bottom: 30px;
  display: block;
}	
</style>
<script type="text/javascript">
  var j = jQuery;
  function load_css(href) {
  	console.log(href);
    remove_template_stylesheets();
     var cssLink = j("<link rel='stylesheet' type='text/css' href='"+href+"'>");
     j("head").append(cssLink);
  }
  function remove_template_stylesheets (){
    j('link[rel=stylesheet][href~="/stylesheets/homes/_template_thermal_responsive.css"]').remove();
  }
  function print_preview() {
    var ifrm = document.getElementById('preview_frame');
    iframe_window=(ifrm.contentWindow || ifrm.contentDocument)
    iframe_window.document.execCommand('print', false, null) || iframe_window.print();
  }
  function set_template(id) {
    j("#loader_image").show();
    reset_iframe_dimensions();
    var iframe = document.getElementById('preview_frame');
    // TODO make https compatiable
    // iframe.src= "<%= "http://localhost:3001/homes/thermal" %>";
    j.get(window.location.protocol+"//"+window.location.host+"/finance/get_dotmatrix_printer_message/"+id)
    iframe.src=window.location.protocol+"//"+window.location.host+"/finance/fees_receipt_preview?type="+id
    if(id==0) {
      // j("#preview_frame").addClass("a4_preview_overrides");
    } else {
      j("#preview_frame").removeClass("a4_preview_overrides");
    }
  }
  function initilize_iframe (obj) {
    resizeIframe(obj);
    j("#loader_image").hide();
    if(current_layout()==0) {
      // j("#preview_frame").addClass("a4_preview_overrides");
    } else {
      j("#preview_frame").removeClass("a4_preview_overrides");
    }
  }
  function current_layout() {
    return j("#receipt_printer_receipt_printer_template").val()
  }
  function resizeIframe(obj) {
    obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
    obj.style.width = obj.contentWindow.document.body.scrollWidth + 'px';
    obj.style.width = obj.contentDocument.documentElement.scrollWidth+'px';
  }
  function reset_iframe_dimensions() {
    var iframe = document.getElementById('preview_frame');
    iframe.style.height=0+ 'px';
    iframe.style.width=0+ 'px';
  }
  j(function() {
    reset_iframe_dimensions();
  });
</script>

app/views/homes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Homes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homes.each do |home| %>
      <tr>
        <td><%= home.name %></td>
        <td><%= home.age %></td>
        <td><%= home.gender %></td>
        <td><%= link_to 'Show', home %></td>
        <td><%= link_to 'Edit', edit_home_path(home) %></td>
        <td><%= link_to 'Destroy', home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Home', new_home_path %>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form', home: @home %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @home.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @home.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @home.gender %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/homes/thermal.html.erb
<%= render "template_thermal_responsive" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThermalPrint</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/print.html.erb
<%- # Fedena
    #Copyright 2010 Foradian Technologies Private Limited
    #
    #This product includes software developed at
    #Project Fedena - http://www.projectfedena.org/
    #
    #Licensed under the Apache License, Version 2.0 (the "License");
    #you may not use this file except in compliance with the License.
    #You may obtain a copy of the License at
    #
    #  http://www.apache.org/licenses/LICENSE-2.0
    #
    #Unless required by applicable law or agreed to in writing,
    #software distributed under the License is distributed on an
    #"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    #KIND, either express or implied.  See the License for the
    #specific language governing permissions and limitations
    #under the License.
-%>

<!DOCTYPE html>
<html dir="<%= 'ltr' %>"  moznomarginboxes mozdisallowselectionprint>
  <head>
    <% @direction = '' %>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title><%="h @title "%></title>
    <% unless true %>
        <link rel="shortcut icon" href="<%= current_school_detail.logo.url(:original, false) %>" type="<%= current_school_detail.logo.content_type %>"/>
    <% end %>

    <%#= stylesheet_link_tag(*get_stylesheets) %>
    <%= javascript_include_tag 'jquery/jquery-1.9.1.min.js' %>

    <%= javascript_include_tag :defaults, :cache => 'cache/javascripts/all' %>
    <%= javascript_include_tag 'fedena_plugin.js' %>
    <%= yield :head %>
    <script type="text/javascript">
      var j = jQuery.noConflict();
    </script>
  </head>
  <body>
    <div id="content_wrapper">
      <div id="content">
        <%= yield %>
      </div>
      <div class="extender"></div>
    </div>
  </body>
</html>